export interface SeedConsultant {
  id: string
  name: string
  title: string
  company: string
  certifications: string[]
  industry: string
  experience: string
  rating: number
  reviewCount: number
  bio: string
  specializations: string[]
  verified: boolean
}

export const seedConsultants: SeedConsultant[] = [
  {
    id: '1',
    name: 'Maria Rodriguez',
    title: 'Federal Contracts Strategist',
    company: 'Rodriguez GovCon Advisory',
    certifications: ['8(a)', 'WOSB'],
    industry: 'IT',
    experience: '10+',
    rating: 4.9,
    reviewCount: 47,
    bio: 'Former DOJ contracting officer with 15 years of federal acquisition experience. Specializes in helping 8(a) and WOSB firms navigate complex multi-agency RFPs and build winning proposal teams.',
    specializations: ['Proposal Strategy', '8(a) Compliance', 'Team Building'],
    verified: true,
  },
  {
    id: '2',
    name: 'James Carter',
    title: 'Defense Contracting Consultant',
    company: 'Carter Defense Solutions',
    certifications: ['SDVOSB'],
    industry: 'Defense',
    experience: '10+',
    rating: 4.8,
    reviewCount: 32,
    bio: 'Disabled veteran and former DoD program manager. Deep expertise in DFARS compliance, MILSPEC requirements, and defense agency procurement processes for small businesses.',
    specializations: ['DFARS', 'DoD Contracts', 'Compliance'],
    verified: true,
  },
  {
    id: '3',
    name: 'Sarah Chen',
    title: 'HUBZone Strategy Consultant',
    company: 'Chen Federal Group',
    certifications: ['HUBZone'],
    industry: 'Professional Services',
    experience: '5-10',
    rating: 4.7,
    reviewCount: 28,
    bio: 'Helped over 50 HUBZone firms secure their first federal contracts. Expertise in GSA Schedule applications, IDIQ proposals, and building long-term agency relationships.',
    specializations: ['HUBZone Strategy', 'GSA Schedules', 'Agency Relations'],
    verified: true,
  },
  {
    id: '4',
    name: 'David Thompson',
    title: 'Construction Federal Specialist',
    company: 'Thompson Build Consulting',
    certifications: ['8(a)'],
    industry: 'Construction',
    experience: '10+',
    rating: 4.6,
    reviewCount: 19,
    bio: '30 years in federal construction contracting. Specializes in NAVFAC, USACE, and GSA construction projects. Helps small firms meet bonding requirements and safety compliance.',
    specializations: ['NAVFAC', 'USACE', 'Bonding'],
    verified: true,
  },
  {
    id: '5',
    name: 'Aisha Patel',
    title: 'Healthcare IT Federal Consultant',
    company: 'Patel Health GovCon',
    certifications: ['WOSB', '8(a)'],
    industry: 'Healthcare',
    experience: '5-10',
    rating: 4.9,
    reviewCount: 41,
    bio: 'Former VA program analyst turned consultant. Bridges the gap between healthcare delivery and federal IT requirements including FISMA, NIST, and FedRAMP compliance.',
    specializations: ['VA Contracts', 'FedRAMP', 'Health IT'],
    verified: true,
  },
  {
    id: '6',
    name: 'Robert Williams',
    title: 'Federal Compliance Advisor',
    company: 'Williams Compliance Group',
    certifications: ['SDVOSB'],
    industry: 'IT',
    experience: '5-10',
    rating: 4.5,
    reviewCount: 15,
    bio: 'Specializes in small business compliance programs including CMMC, ITAR, and SOC 2 for federal contractors. Helps firms avoid costly compliance failures during contract performance.',
    specializations: ['CMMC', 'ITAR', 'Audit Prep'],
    verified: true,
  },
  {
    id: '7',
    name: 'Lisa Garcia',
    title: 'Proposal Development Manager',
    company: 'Garcia Proposal Works',
    certifications: ['8(a)', 'HUBZone'],
    industry: 'Professional Services',
    experience: '3-5',
    rating: 4.4,
    reviewCount: 12,
    bio: 'Professional proposal writer and graphic designer for federal submissions. Creates compelling past performance narratives, management plans, and compliance matrices.',
    specializations: ['Proposal Writing', 'Graphic Design', 'Compliance Matrix'],
    verified: false,
  },
  {
    id: '8',
    name: "Michael O'Brien",
    title: 'IT Federal Contracts Advisor',
    company: "O'Brien Tech Advisors",
    certifications: ['SDVOSB'],
    industry: 'IT',
    experience: '10+',
    rating: 4.7,
    reviewCount: 36,
    bio: 'Former IRS IT division chief. Deep knowledge of federal IT procurement including cloud services, cybersecurity contracts, and software licensing under FAR Part 12.',
    specializations: ['Cloud Services', 'Cybersecurity', 'FAR Part 12'],
    verified: true,
  },
  {
    id: '9',
    name: 'Karen Foster',
    title: 'SAM.gov & Registration Expert',
    company: 'Foster Federal Prep',
    certifications: ['8(a)'],
    industry: 'Professional Services',
    experience: '3-5',
    rating: 4.3,
    reviewCount: 8,
    bio: 'Guides new federal contractors through SAM.gov registration, CAGE code setup, and small business certifications. Makes the onboarding process fast and error-free.',
    specializations: ['SAM.gov', 'CAGE Codes', 'Certification Prep'],
    verified: false,
  },
  {
    id: '10',
    name: 'Thomas Jackson',
    title: 'Construction Compliance Specialist',
    company: 'Jackson FedCon Services',
    certifications: ['HUBZone'],
    industry: 'Construction',
    experience: '5-10',
    rating: 4.6,
    reviewCount: 22,
    bio: 'Expert in Davis-Bacon Act compliance, small business subcontracting plans, and construction contract administration for HUBZone firms in the Southeast region.',
    specializations: ['Davis-Bacon', 'Subcontracting Plans', 'Contract Admin'],
    verified: true,
  },
  {
    id: '11',
    name: 'Priya Sharma',
    title: 'Federal Financial Analyst',
    company: 'Sharma GovCon Finance',
    certifications: ['WOSB'],
    industry: 'IT',
    experience: '5-10',
    rating: 4.8,
    reviewCount: 29,
    bio: 'CFO-level advisor for federal contractors. Helps small businesses with cost accounting, indirect rate development, and financial systems that meet DCAA audit requirements.',
    specializations: ['DCAA Compliance', 'Cost Accounting', 'Indirect Rates'],
    verified: true,
  },
  {
    id: '12',
    name: 'Anthony Martinez',
    title: 'Defense Logistics Consultant',
    company: 'Martinez DLA Advisors',
    certifications: ['8(a)', 'SDVOSB'],
    industry: 'Defense',
    experience: '10+',
    rating: 4.5,
    reviewCount: 18,
    bio: 'Former DLA procurement analyst with expertise in supply chain contracts, spare parts procurement, and DLA\'s small business programs. Veteran-owned business advocate.',
    specializations: ['DLA Contracts', 'Supply Chain', 'Small Business Programs'],
    verified: true,
  },
]